MAIN_FUNC_PATH = main.c
CONFIG_PATH = ../config
PREF_DEP = dependency
DEPENDENCY_SRC = $(shell find $(PREF_DEP) -name '*.c')
INC_FOLDERS += \
	.
PREF_MODULE = ../src/modules
SRC_DIR = ../src
LINKER_SCRIPT  = ../estc_adverts_gcc_nrf52.ld

include ../Makefile
