CONFIG := ../../config
LINKER_SCRIPT := ../blinky_gcc_nrf52.ld

PREF_TEST_SRC = ../../test/test_main.c

PROJ_DIR := ../../src/test
DEPENDENCY_SRC = $(shell find ../$(PREF_DEP) -name '*.c')

debug:
	echo $(SRC_FILES)

include ../Makefile.common